import { View, Text, StyleSheet, Image, TextInput, TouchableOpacity, KeyboardAvoidingView, Platform, ActivityIndicator, BackHandler, ScrollView } from 'react-native'
import { showAlert } from '../../components/AppAlert'
import { useState, useEffect } from 'react'
import { Ionicons } from "@expo/vector-icons"
import { useRouter } from 'expo-router';
import COLORS from '../../constants/colors';
import styles from '../../assets/styles/authStyle/signup.style';
import { isAllowedEmail, EMAIL_DOMAIN_ERROR } from '../../lib/emailValidator';

import {useAuthStore} from "../../store/authStore"

const TERMS_TEXT = `Welcome to VisionFIT360. By creating an account, you agree to the following:

1. ACCOUNT RESPONSIBILITY
You are responsible for maintaining the confidentiality of your login credentials and for all activity under your account.

2. FITNESS & HEALTH DISCLAIMER
VisionFIT360 provides workout tracking, AI-generated exercise recommendations, and AR-based rep counting for informational purposes only. It is not a substitute for professional medical or fitness advice. Consult a physician before beginning any new exercise program, especially if you have a pre-existing health condition. You use this app and perform all exercises at your own risk.

3. AI-GENERATED CONTENT
Workout recommendations are generated by an AI system and may not be suitable for every fitness level or medical condition. Use your judgment and stop any exercise that causes pain or discomfort.

4. DATA USAGE
We store the profile and workout data you provide (such as height, weight, and workout history) to power features like BMI calculation and personalized recommendations. We do not sell your personal data to third parties.

5. ACCOUNT TERMINATION
We reserve the right to suspend or terminate accounts that violate these terms or misuse the platform.

By checking the box below, you confirm that you have read, understood, and agree to these terms.`;

export default function Signup() {
const router = useRouter();
const [username, setUsername] = useState("");
const [email, setEmail] = useState("");
const [password, setPassword] = useState("");
const [showPassword, setShowPassword] = useState(false);
const [agreedToTerms, setAgreedToTerms] = useState(false);
const [showTerms, setShowTerms] = useState(false);

const {user, isLoading, register, token} = useAuthStore();

// ---- email domain check (live) ----
// only show the inline error once the user has typed a full-looking domain (e.g. "name@abc.com")
const emailDomain = email.trim().split("@")[1] || "";
const showEmailError = emailDomain.includes(".") && !isAllowedEmail(email);

// ---- password rule checks (live) ----
const hasMinLength = password.length >= 8;
const hasLetter = /[a-zA-Z]/.test(password);
const hasNumber = /[0-9]/.test(password);
const isValidPassword = hasMinLength && hasLetter && hasNumber;

// strength: weak / medium / strong
const getStrength = () => {
  if (!password) return { label: "", level: 0, color: COLORS.border };
  let score = 0;
  if (hasMinLength) score++;
  if (hasLetter) score++;
  if (hasNumber) score++;
  if (password.length >= 12 || /[^a-zA-Z0-9]/.test(password)) score++;
  if (score <= 2) return { label: "Weak", level: 1, color: "#E24B4A" };
  if (score === 3) return { label: "Medium", level: 2, color: "#E2A33B" };
  return { label: "Strong", level: 3, color: "#1D9E75" };
};
const strength = getStrength();

//  ANDROID HARDWARE BACK BUTTON (closes terms modal if open) 
useEffect(() => {
  const backAction = () => {
    if (showTerms) { setShowTerms(false); return true; }
    return false;
  };
  const sub = BackHandler.addEventListener('hardwareBackPress', backAction);
  return () => sub.remove();
}, [showTerms]);

const handleSignUp = async () => {
  // client-side guard (backend still enforces it too)
  if (!isAllowedEmail(email)) {
    showAlert("Invalid Email", EMAIL_DOMAIN_ERROR);
    return;
  }
  if (!isValidPassword) {
    showAlert("Weak Password", "Password must be at least 8 characters and include a letter and a number.");
    return;
  }
  if (!agreedToTerms) {
    showAlert("Terms required", "Please agree to the Terms & Conditions to continue.");
    return;
  }
  const result = await register(username, email, password);
  if(!result.success) {
      showAlert("Error", result.error);
      return;
  } 
  router.replace({ pathname: "./verify-email", params: { email } });
};

  return (
     <KeyboardAvoidingView
      style={{ flex: 1 }}
      behavior={Platform.OS === "ios" ? "padding" : "height"}
     >
    <ScrollView contentContainerStyle={styles.container} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>
      <View style={styles.card}>
        <Text style={styles.title}>Sign up</Text>
        <View style={styles.formContainer}>
                   {/* Username */}
        <View style={styles.inputGroup}>
          <Text style={styles.label}>Username</Text>
          <View style={styles.inputContainer}>
              <Ionicons 
                name="person"
                size={20}
                color={COLORS.black}
                style={styles.inputIcon}
              />
              <TextInput
                style={styles.input}
                placeholder="Username"
                placeholderTextColor={COLORS.black}
                onChangeText={setUsername} 
                value={username}
                autoCapitalize="none"
                maxLength={30}
              />
          </View>
        </View>
                  {/* Email */}
        <View style={styles.inputGroup}>
          <Text style={styles.label}>Email</Text>
          <View style={styles.inputContainer}>
            <Ionicons 
              name="mail"
              size={20}
              color={COLORS.black}
              style={styles.inputIcon}
            />
            <TextInput
              style={styles.input}
              placeholder="Email"
              value={email}
              placeholderTextColor={COLORS.black}
              onChangeText={setEmail}
              keyboardType="email-address"
              autoCapitalize="none"
              maxLength={100}
            />
          </View>
          {showEmailError && (
            <Text style={pwStyles.emailError}>{EMAIL_DOMAIN_ERROR}</Text>
          )}
        </View>
               {/* Password */}
        <View style={styles.inputGroup}>
          <Text style={styles.label}>Password</Text>
          <View style={styles.inputContainer}>
            <Ionicons
              name="lock-closed"
              size={20}
              color={COLORS.primary}
              style={styles.inputIcon}
            />
            <TextInput
              style={styles.input}
              placeholder="Password"
              placeholderTextColor={COLORS.black}
              value={password}
              onChangeText={setPassword}
              secureTextEntry={!showPassword}
              maxLength={64}
            />
            <TouchableOpacity onPress={() => setShowPassword(!showPassword)} style={styles.eyeIcon}>
               <Ionicons
                 name={showPassword ? "eye" : "eye-off"}
                 size={20}
                 color={COLORS.black}
               />
            </TouchableOpacity>
          </View>

          {/* Strength meter + checklist (only show when typing) */}
          {password.length > 0 && (
            <View style={pwStyles.feedbackWrap}>
              <View style={pwStyles.meterRow}>
                <View style={[pwStyles.meterSegment, { backgroundColor: strength.level >= 1 ? strength.color : COLORS.border }]} />
                <View style={[pwStyles.meterSegment, { backgroundColor: strength.level >= 2 ? strength.color : COLORS.border }]} />
                <View style={[pwStyles.meterSegment, { backgroundColor: strength.level >= 3 ? strength.color : COLORS.border }]} />
              </View>
              {!!strength.label && (
                <Text style={[pwStyles.strengthLabel, { color: strength.color }]}>{strength.label}</Text>
              )}
              <View style={pwStyles.checkRow}>
                <Ionicons name={hasMinLength ? "checkmark-circle" : "ellipse-outline"} size={14} color={hasMinLength ? "#1D9E75" : COLORS.gray} />
                <Text style={pwStyles.checkText}>At least 8 characters</Text>
              </View>
              <View style={pwStyles.checkRow}>
                <Ionicons name={hasLetter ? "checkmark-circle" : "ellipse-outline"} size={14} color={hasLetter ? "#1D9E75" : COLORS.gray} />
                <Text style={pwStyles.checkText}>Contains a letter</Text>
              </View>
              <View style={pwStyles.checkRow}>
                <Ionicons name={hasNumber ? "checkmark-circle" : "ellipse-outline"} size={14} color={hasNumber ? "#1D9E75" : COLORS.gray} />
                <Text style={pwStyles.checkText}>Contains a number</Text>
              </View>
            </View>
          )}
        </View>

        {/* Terms checkbox */}
        <View style={pwStyles.termsRow}>
          <TouchableOpacity onPress={() => setAgreedToTerms(!agreedToTerms)} hitSlop={8}>
            <Ionicons
              name={agreedToTerms ? "checkbox" : "square-outline"}
              size={22}
              color={agreedToTerms ? COLORS.button : COLORS.gray}
            />
          </TouchableOpacity>
          <Text style={pwStyles.termsText}>
            I agree to the{" "}
            <Text style={pwStyles.termsLink} onPress={() => setShowTerms(true)}>
              Terms &amp; Conditions
            </Text>
          </Text>
        </View>
        </View>
         <TouchableOpacity
           style={[styles.button, ((!isValidPassword && password.length > 0) || !agreedToTerms || showEmailError) && { opacity: 0.6 }]}
           onPress={handleSignUp}
           disabled={isLoading}
         >
            {isLoading ? (
              <ActivityIndicator color="#fff" />
              ) : (
              <Text style={styles.buttonText}>Sign Up</Text>
            )}
        </TouchableOpacity>
                  {/* Footer */}
        <View style={styles.footer}>
           <Text style={styles.footerText}>Already have an account?</Text>
           <TouchableOpacity onPress={() => router.back()}>
              <Text style={styles.link}>Login</Text>
           </TouchableOpacity>
        </View>
      </View>
    </ScrollView>

    {/*  TERMS & CONDITIONS MODAL  */}
    {showTerms && (
      <View style={{ position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, zIndex: 80, elevation: 80 }}>
        <View style={{ flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'center', alignItems: 'center', padding: 20 }}>
          <View style={{ backgroundColor: COLORS.white, borderRadius: 20, overflow: 'hidden', width: '100%', maxWidth: 480, maxHeight: '80%' }}>
            <View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 20, borderBottomWidth: 1, borderBottomColor: COLORS.border }}>
              <Text style={{ fontSize: 18, fontWeight: '700', color: COLORS.black }}>Terms &amp; Conditions</Text>
              <TouchableOpacity onPress={() => setShowTerms(false)}>
                <Ionicons name="close" size={24} color={COLORS.black} />
              </TouchableOpacity>
            </View>
            <ScrollView contentContainerStyle={{ padding: 20 }}>
              <Text style={{ fontSize: 13, color: COLORS.gray, lineHeight: 20 }}>{TERMS_TEXT}</Text>
            </ScrollView>
            <TouchableOpacity
              style={{ backgroundColor: COLORS.button, borderRadius: 12, padding: 14, alignItems: 'center', margin: 20, marginTop: 8 }}
              onPress={() => { setAgreedToTerms(true); setShowTerms(false); }}
            >
              <Text style={{ color: COLORS.white, fontSize: 15, fontWeight: '700' }}>I Agree</Text>
            </TouchableOpacity>
          </View>
        </View>
      </View>
    )}
    </KeyboardAvoidingView>
  )
}

// local styles for the password feedback (kept separate so your main style file stays untouched)
const pwStyles = StyleSheet.create({
  emailError: { fontSize: 12, color: "#E24B4A", marginTop: 6 },
  feedbackWrap: { marginTop: 10 },
  meterRow: { flexDirection: "row", gap: 6, marginBottom: 6 },
  meterSegment: { flex: 1, height: 6, borderRadius: 3, backgroundColor: COLORS.border },
  strengthLabel: { fontSize: 12, fontWeight: "600", marginBottom: 6 },
  checkRow: { flexDirection: "row", alignItems: "center", gap: 6, marginBottom: 2 },
  checkText: { fontSize: 12, color: COLORS.gray },
  termsRow: { flexDirection: "row", alignItems: "flex-start", gap: 8, marginTop: 4 },
  termsText: { flex: 1, fontSize: 13, color: COLORS.gray, lineHeight: 18 },
  termsLink: { color: COLORS.button, fontWeight: "600" },
});